version: '3.9'

services:

  redis:
    image: redis:latest
    container_name: redis-server
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--auth"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      timeout: 20s
      retries: 10
    restart: always
      

  minio:
    image: minio/minio
    env_file:
      - .env
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:9000/minio/health/live" ]
      timeout: 20s
      retries: 10
    restart: always

  app:
    entrypoint: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  redis-data:
  mongodb-data:
  minio-data:
